apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-static-argo-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/TanvirMahin24/kubernetes-config.git
    targetRevision: HEAD
    path: nginx-argocd-config
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp
  
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
