kind: Deployment
apiVersion: apps/v1
metadata:
  name: react-docker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-docker
  template:
    metadata:
      labels:
        app: react-docker
    spec:
      containers:
      - name: react-docker
        image: tanvirmahin24/static-nginx-site
        resources:
            limits:
              memory: 100Mi
              cpu: "1"
        ports:
        - containerPort: 80